//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdditionalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdditionalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp.AdditionalResources", typeof(AdditionalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;cd__headline-text&quot;&gt;Hypersonic engine may &apos;revolutionize&apos; flying&lt;/span&gt;.
        /// </summary>
        internal static string HtmlCodeExample {
            get {
                return ResourceManager.GetString("HtmlCodeExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 class=&quot;cd__headline&quot; data-analytics=&quot;Top%20Stories_list-hierarchical-xs_article_&quot;&gt;
        ///&lt;a href=&quot;/2015/11/04/europe/romania-pm-ponta-resigns/index.html&quot; onclick=&quot;CNN.Analytics.utils.clickEventTracker(event, &apos;hpt=cGFnZV8xNGNvbF9pbnRsX2hvbWVwYWdlX2luZGV4X3pvbmUtMC0wX1pvbmUgMV9jbi1jb250YWluZXJfMDI1RTZDNjMtNDkzNS0yMzEzLUExQjUtOEJDMzQ5QUY3REJBX1RvcCUyMFN0b3JpZXM=;hpt2=cGFnZV8xNGNvbF9pbnRsX2hvbWVwYWdlX2luZGV4X3pvbmUtMC0wX25vLXZhbHVlLXNldF9jbi1jb250YWluZXJfMDI1RTZDNjMtNDkzNS0yMzEzLUExQjUtOEJDMzQ5QUY3REJBX2xlYWQrbG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlCodeExample2 {
            get {
                return ResourceManager.GetString("HtmlCodeExample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul class=&quot;el__storyhighlights__list&quot;&gt;
        ///&lt;li class=&quot;el__storyhighlights__item el__storyhighlights--new&quot;&gt; Three people, including a baby, survived the crash, presidential spokesman says&lt;/li&gt;
        ///&lt;li class=&quot;el__storyhighlights__item el__storyhighlights--normal&quot;&gt;Plane crashed shortly after takeoff&lt;/li&gt;
        ///&lt;li class=&quot;el__storyhighlights__item el__storyhighlights--normal&quot;&gt;Flight was bound for oil-rich northern part of the country&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        internal static string HtmlCodeExample3 {
            get {
                return ResourceManager.GetString("HtmlCodeExample3", resourceCulture);
            }
        }
    }
}
